// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	HACKER_NEWS_KV: KVNamespace;
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	NEXTJS_ENV: string;
	NEXT_STATIC_HOST: string;
	OPENAI_API_KEY: string;
	OPENAI_BASE_URL: string;
	OPENAI_MODEL: string;
	AUDIO_VOICE_ID: string;
	HACKER_NEWS_R2: R2Bucket;
	ASSETS: Fetcher;
	HACKER_NEWS_WORKFLOW: Workflow;
}
