name = "hacker-news"
main = ".open-next/server/index.js"
compatibility_date = "2024-01-01"

[vars]
NEXTJS_ENV = "development"
NEXT_STATIC_HOST = "http://localhost:3000/static"

[[kv_namespaces]]
binding = "HACKER_NEWS_KV"
id = "027cae8cabcc4c6787c70827804a726e"
preview_id = "027cae8cabcc4c6787c70827804a726e"

[build]
command = "pnpm build"
